help = "Помогите 🙁"
pidor = "Сегодняшний пидор"
stats_total = "Че там по пидорам за все время?"
stats_year = "Че там по пидорам за весь год?"
stats_month = "Че там по пидорам за весь месяц?"
rage = "Сделай боту больно. Пройдет через 10 минут или 20 сообщений. Работает раз в день."
leaderboard = "Лучшие среди нас"
answer = "Преодолеть муки выбора. Использование: [вариант] или [другой вариант] (сколько угодно \"или\")"
bet = "БЫСТРЫЕ ВЫПЛАТЫ, НАДЕЖНЫЙ БУКМЕКЕР"
ask_world = "Спроси мир. Для подробностей вызовите команду."
me = "Ваша пидорская статистика"
settings = "Опции внутри чата"
advanced_settings = "Опции для хакеров"
play = "Коллективная пошаговая игруля для чата"
stats_strikes = "Рейтинг пидоров, выпавших подряд"
shop = "Магазин Сучары"
marry = "браки между участниками"
marry_list = "Топ браков чата"
summary = "Выжимка последних 100 сообщений. В тестовом режиме пока."
reactions = "[ТЕСТ] Статистика по реакциям в чате."