quotes = [
    { tag = "городецкий", quote = "Люцифер в аду возводит безумную скульптуру ЗЛА!" },
    { tag = "городецкий", quote = "Я слышу голос овощей!!!" },
    { tag = "городецкий", quote = "УУУУУУБЕЕЕЕЕЙЙ! Кричали голоса!" },
    { tag = "городецкий", quote = "Купи котенка СВОЕМУ РЕБЕНКУ!" },
    { tag = "городецкий", quote = "Денчик ушел в метал!" },
    { tag = "городецкий", quote = "Безумец! Слепой! Остановиииись!" },
    { tag = "городецкий", quote = "Черный толчок смерти уубииваает..." },
    { tag = "городецкий", quote = "УБЕЙ ВСЮ СВОЮ СЕМЬЮ" },
    { tag = "городецкий", quote = "Траву жрет корова! Корову жрет человек! Человека жрет пожарник! Пожарника сожрет пламя.." },
    { tag = "городецкий", quote = "Свой собственный сын" },
    { tag = "городецкий", quote = "Дирижабль упал в стадо коров!" },
    { tag = "городецкий", quote = "Рыыыыбааааа..." },
    { tag = "городецкий", quote = "Купи йогурт-смерть в подарок" },
    { tag = "городецкий", quote = "Платформа справа-КРОВАВАЯ РАСПРАВА!" },
    { tag = "бау", quote = "Люцифер в аду возводит безумную скульптуру ЗЛА!" },
    { tag = "бау", quote = "Я слышу голос овощей!!!" },
    { tag = "бау", quote = "УУУУУУБЕЕЕЕЕЙЙ! Кричали голоса!" },
    { tag = "бау", quote = "Я ненавижу Питер!" },
    { tag = "бау", quote = "Купи котенка СВОЕМУ РЕБЕНКУ!" },
    { tag = "бау", quote = "Денчик ушел в метал!" },
    { tag = "бау", quote = "Безумец! Слепой! Остановиииись!" },
    { tag = "бау", quote = "Черный толчок смерти уубииваает..." },
    { tag = "бау", quote = "УБЕЙ ВСЮ СВОЮ СЕМЬЮ" },
    { tag = "бау", quote = "Траву жрет корова! Корову жрет человек! Человека жрет пожарник! Пожарника сожрет пламя.." },
    { tag = "бау", quote = "Свой собственный сын" },
    { tag = "бау", quote = "Дирижабль упал в стадо коров!" },
    { tag = "бау", quote = "Рыыыыбааааа..." },
    { tag = "бау", quote = "Купи йогурт-смерть в подарок" },
    { tag = "бау", quote = "Платформа справа-КРОВАВАЯ РАСПРАВА!" },
    { tag = "бау", quote = "Залетел к нам на хату блатной ветерок!" },
    { tag = "бау", quote = "Ты не шахтер, но лазишь в шахты" },
    { tag = "бау", quote = "Не трубочист, но чистишь дымоход" },
    { tag = "бау", quote = "Лупишься в туза, но не играешь в карты" },
    { tag = "бау", quote = "Не вор, но знаешь всё про черный ход" },
    { tag = "бау", quote = "Ты не гончар, но месишь глину" },
    { tag = "бау", quote = "Ты не лесник, но шебуршишь в дупле" },
    { tag = "бау", quote = "Волосатый мотороллер едет без резины" },
    { tag = "бау", quote = "Твоя кожаная пуля в кожаном стволе" },
    { tag = "ярик", quote = "Почему для жирных волос шампунь есть, а для жирных людей-нет? " },
    { tag = "ярик", quote = "Всегда мечтал поставить турель!" },
    { tag = "ярик", quote = "О, молочко!" },
    { tag = "ярик", quote = "Бляяя, охуенно посрал!" },
    { tag = "ярик", quote = "Корки оставьте, я через неделю доем" },
    { tag = "пиздюк", quote = "Я ненавижу Питер!" },
    { tag = "павлик", quote = "Калифоникеееееейшн" },
    { tag = "павлик", quote = "Залетел к нам на хату блатной ветерок!" },
    { tag = "витя", quote = "Шлики-шлики" },
    { tag = "lol", quote = "Володю не баньте, я в лес иду!" },
    { tag = "lol", quote = "Ярик, заебись копьё кинул" },
    { tag = "lol", quote = "Ари, шалунья, через стены скачет" },
    { tag = "хампик", quote = "Все, блять, справедливо, сука!" },
    { tag = "хампик", quote = "Ебал я эту хуйню в рот!" },
    { tag = "хампик", quote = "Мне похуй, что мы побеждаем, мы все равно проебем! " },
    { tag = "хампик", quote = "Володю не баньте, я в лес иду!" },
    { tag = "тима", quote = "Ты не шахтер, но лазишь в шахты " },
    { tag = "тима", quote = "Не трубочист, но чистишь дымоход" },
    { tag = "тима", quote = "Лупишься в туза, но не играешь в карты" },
    { tag = "тима", quote = "Не вор, но знаешь всё про черный ход" },
    { tag = "тима", quote = "Ты не гончар, но месишь глину" },
    { tag = "тима", quote = "Ты не лесник, но шебуршишь в дупле" },
    { tag = "тима", quote = "Волосатый мотороллер едет без резины" },
    { tag = "тима", quote = "Твоя кожаная пуля в кожаном стволе" },
    { tag = "тима", quote = "А ну съябывай с компа и стула!" },
    { tag = "тима", quote = "Хэд энд шордлз!" },
    { tag = "тима", quote = "Эта икра недостаточно красная!" },
    { tag = "тима", quote = "Планету взорвали? АЛЬДЕБАРАН!" },
    { tag = "ярик", quote = "А вот бы" },
    { tag = "серый", quote = "Ты сам себе противоречишь!" },
    { tag = "серый", quote = "Твои слова - абзац википедии" },
    { tag = "павлик", quote = "Любимый актер? Моргл Фриман" },
    { tag = "серый", quote = "WAHT!?!?" },
    { tag = "серый", quote = "Это еще шозахуйня!?" },
    { tag = "серый", quote = "Ситуёвина такая..." },
    { tag = "серый", quote = "Этот пряник настроен культурно отдохнуть" },
    { tag = "тима", quote = "Я, конечно, люблю клубничку, но шоколад мне больше нравится " },
    { tag = "тима", quote = "Да, пупсик, я тебя слушаю..." },
    { tag = "городецкий", quote = "... А из очка вылез... ЛЕЕЕЕОООКК!!!!!!!!" },
    { tag = "кирилл", quote = "Жесть ты дикий хаслер" },
    { tag = "архипыч", quote = "У тебя охуение личности?" },
    { tag = "архипыч", quote = "Шаурма слишком быстро съедается" },
    { tag = "архипыч", quote = "Почему твоя правая рука собралась стать принцесской французской?" },
    { tag = "архипыч", quote = "Хочешь расскажу слизливую историю, как я из 4 платины скатился в 5 золото?" },
    { tag = "павлик", quote = "Ты бы видел её лицо, когда я сказал, что там пиздёнки даже принцессы месяцами не мыли" },
    { tag = "пиздюк", quote = "Я КОРОЛЬ ЯЩЕРИЦ" },
    { tag = "павлик", quote = "БАСССЕЕЕЕЙН" },
    { tag = "серый", quote = "Ярик, заебись копьё кинул" },
    { tag = "серый", quote = "Ари, шалунья, через стены скачет" },
    { tag = "хампик", quote = "Зачем ты под черного легла?" },
    { tag = "тима", quote = "КОТЛЕТКИ! ТАМ БЫЛИ КРОВАВЫЕ КОТЛЕТКИ!!!!!!!!!!!!!!" },
    { tag = "архипыч", quote = "Онанист чертов, будь ты проклят!" },
    { tag = "ярик", quote = "СЛОУУУУПОООООК!" },
    { tag = "серый", quote = "Скажи \"от того самого\" он поймет" },
    { tag = "killagram", quote = "Я за эвтаназию, но против массажа простаты" },
    { tag = "killagram", quote = "А ты думала мы тут будем ебаться как кролики?" },
    { tag = "killagram", quote = "Кто ты такой?" },
    { tag = "killagram", quote = "Протыкает кожу четко, пробивает мышц и хрящ его длинная отвертка прямо в ляжку ХАЩ ХАЩ" },
    { tag = "killagram", quote = "Шаг назад для контратаки. ПОЛУЧАЙТЕ ВУРДАЛАКИ!" },
    { tag = "killagram", quote = "Вы кто такие!? ХУЛЕ ВАМ ЗДЕСЬ НУЖНО!?" },
    { tag = "killagram", quote = "Вот только я не Павел..." },
    { tag = "killagram", quote = "...с тех пор Жека стал легендой ЖЭКа" },
    { tag = "killagram", quote = "Это охуительный был аттракцион!" },
    { tag = "killagram", quote = "ЭТО ЗАХАР ВЫПУСКАЕТ ПАР!" },
    { tag = "killagram", quote = "Ромааааан понял, хоть и юродивый: место  мусора  в МУСОРОПРОВОДЕ" },
    { tag = "killagram", quote = "Пойдем убьем снеговика!" },
    { tag = "killagram", quote = "Борщ - это мощь!" },
    { tag = "killagram", quote = "Даже за бабки от бабки с косою не удалось откосить никому!!!!!" },
    { tag = "killagram", quote = "Проверка микрофона! Чек-чек три-четыре!" },
    { tag = "killagram", quote = "...А Аня бежит со всех ног по дороге, за нею бегут мусорааааа, чтобы дать пиздюююююлеееееееей" },
    { tag = "пиздюк", quote = "Дайте мне спокойно умереть!" },
    { tag = "ярик", quote = "Ты новощь!" },
    { tag = "городецкий", quote = "Во время еды праздник елды" },
    { tag = "кирилл", quote = "Вибрация начинается до звука" },
    { tag = "пиздюк", quote = "Пивас, спокойствие и личные успехи - лучшие пацанские доспехи" },
    { tag = "кирилл", quote = "Ебобошечки когда покурим?" },
    { tag = "кирилл", quote = "Погоди, а кто тогда работу работает?" },
    { tag = "кирилл", quote = "Будем курить альфак)))))))" },
    { tag = "кирилл", quote = "Увы сам несколько раз был свидетелем как ренгар собирает драктар и ваншотает любого" },
    { tag = "ярик", quote = "У нас там всё в облаках" },
    { tag = "ярик", quote = "Мой Ярик ебашит вообще адовые блюда.  Ну такой вот примерно рецепт усредненный, потому что вариаций масса. Берется пачка останкинских пельменей по 50р за почку по скидке на грани срока годности, они не заморожены, замораживать - это не про моего Ярика. Он берет эти пельмени, вываливает их в мультиварку вместе с прилипшим картоном, ставит режим «горячее копчение» и начинает готовить под давлением. Все это готовится до дыма. Спустя примерно 2 часа открывает крышку мультиварки даже предварительно не спустив пар, крышке позавидует даже Илон Макс. Добавляет в эту прессованную смесь из теста, «мяса» и картона огромное количество майонеза, приправ и кетчуп и начинает есть. При этом ест с кастрюли, шкрябая по ней ложкой. Ест и приговаривает полушепотом ух бля. При этом у него на лбу аж пот выступает. Любезно мне иногда предлагает, но я отказываюсь. Надо ли говорить о том какой дичайший пердеж потом? Вонища такая, что обои от стен отклеиваются." },
    { tag = "ярик", quote = "Техподдержка, Ярослав" },
]
