settings:
  botname: { name }
  token: { token }
  developer: { name }
spring:
  redis:
    host: { redis-host }
    port: { redis-port }
  datasource:
    url: { url }
    driver-class-name: "org.postgresql.Driver"
    password: { password }
    username: { user }
management:
  metrics:
    enable: false
---
settings:
  botname: { name }
  token: { token }
  developer: { name }
spring:
  redis:
    host: { redis-host }
    port: { redis-port }
  datasource:
    url: { url }
    driver-class-name: "org.postgresql.Driver"
    password: { password }
    username: { user }
  profiles: production
management:
  metrics:
    enable: true
    export:
      graphite:
        host: { host }
        port: { port }



